name: CI

on:
  push:
    branches: [master]
    tags:
      - '*'
  pull_request:
    branches: [master]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: pip install scons markdown

      - name: Install Gettext and Poedit
        run: |
          choco install gettext poedit -y
          echo "C:\Program Files\gettext-iconv\bin" >> $env:GITHUB_PATH
          echo "C:\Program Files (x86)\Poedit\GettextTools\bin" >> $env:GITHUB_PATH

      - name: Verify Installation
        run: |
          msgfmt --version
          scons --version

      - name: Run Scons
        run: scons

      - name: Create and Upload Release
        if: contains(github.ref, '/tags/')
        uses: softprops/action-gh-release@v1
        with:
          prerelease: ${{ endsWith(github.ref, '-dev') }}
          files: '*.nvda-addon'
